### ISSUE TITLE
[Question] Supply duration to request.dynamic 

### ISSUE THREAD

**Issue by scottgrobinson** [dtcooper/crazyarms#1]
Hello!

Creating an "autodj" that pulls from another source, which works great, but I'd like to pass the duration. The third part source has duration/fade out as a metadata tag, so if we use the file duration we sometimes get extended silence before the next track starts. 

Do you know if it's possible to supply a duration along with the filepath? I'm struggling to see if that is possible for liquidsoap docs.

```
# Auto DJ1
mairlistautodj = request.dynamic.list(
	# TODO: conservative always keeps one request in the queue, useful for skipping but
	# means station ID + could come several minutes afterwards. I think this isn't needed
	# but if we observe transitions to fallback from autoDJ unexpected this may need to be re-enabled
	id='mairlistautodj', conservative=false, length=REQUEST_QUEUE_LENGTH,
	retry_delay=REQUEST_RETRY_DELAY, timeout=REQUEST_TIMEOUT, fun() -> begin
		url = 'http://10.0.0.4:8123/getnext'
                #url = '#{API_PREFIX}next-track/'
                log('SCOTT #{url}')
		let ((_, status_code, _), _, response) = http.get(url, headers=API_HEADERS)
		if status_code == 200 then
		        asset_uri = list.assoc(default='', 'asset_uri', of_json(default=[('_', '')], response))
			log('mairlistautodj: selected URI #{asset_uri}')
			[request.create(asset_uri)]
		else
			log('ERROR: mairlistautodj: got non-200 status got API (#{status_code}) for next track')
			[]
		end
	end)

mairlistautodj = audio_to_stereo(id='mairlistautodj_to_stereo', mairlistautodj)
mairlistautodj = on_end(id='mairlistautodj_onend', delay=0., fun(_, _) -> begin
	# Clear status since timed_sources may be the only thing that changed
	last_status_without_timed_sources := reset_status
end, mairlistautodj)

# Having mairlistautodj safe for a few seconds means resolution loading files won't
# transition to failsafe and just have a few seconds of silence
#add_skip_command_crazyarms(mairlistautodj)

source_hierarchy = [
    (prerecord, 'Prerecorded Broadcast'),
    (dj_harbor, 'Live DJ'),
    (zoom, 'Zoom Room'),
    (mairlistautodj, 'mAirList AutoDJ'),
    (autodj, 'AutoDJ'),
    (failsafe, FAILSAFE_SOURCE_NAME)
]
```

**Comment by dtcooper** [comment]
Wow! I didn't think anyone was using this pre-v1! I'll take a look tomorrow, but feel free to email me as well david.cooper@burningman.org

I guess this means I should stop overwriting the Django migrations so you have a clean upgrade path. 😛

**Comment by scottgrobinson** [comment]
Ha! Suprise.... I'll drop you an email with our plans/use case as it may be interesting to hear, but fortunately, my colleague found the answer to this one yesterday.

Changing

```
mairlistautodj = audio_to_stereo(id='mairlistautodj_to_stereo', mairlistautodj)
```

to

```
mairlistautodj = cue_cut(mairlistautodj)
mairlistautodj = audio_to_stereo(id='mairlistautodj_to_stereo', mairlistautodj)
```

and adding 'liq_cue_out' to the annotation response from the external URL provided me with the desired outcome :)

**Comment by dtcooper** [comment]
Great! I'll let you know when v0.0.1 is cut, at that point, migration path should be smooth, ie both documented **AND** DB changes will migrate smoothly with [Django migrations](https://docs.djangoproject.com/en/3.1/topics/migrations/). 😄

**Comment by dtcooper** [comment]
All right! `0.0.1-alpha1` is cut! Django migrations _are now guaranteed_ between alpha releases. :)

Also, you can use `./compose.sh pull` now. No need to build containers from source!

**Comment by scottgrobinson** [comment]
git pull, ./compose.sh down -v, ./compose.sh pull, ./compose.sh up -d, re-ran setup and we're semi back in business!

I'll post a new ticket for that issue :)
