### ISSUE TITLE
0.0.1-alpha1 Unable to access "Liquidsoap harbor source code"

### ISSUE THREAD

**Issue by scottgrobinson** [dtcooper/crazyarms#2]
/admin/settings/harbor-custom-config/ returns the following post "clean" upgrade/re-install to 0.0.1-alpha1 from the dev version.

```
Not Found
The requested resource was not found on this server.
```

App container gives the following:

```
today at 09:58  [2021-03-24 09:58:35,190] WARNING:django.request:224:log_response: Not Found: /admin/settings/harbor-custom-config/
```

**Comment by dtcooper** [comment]
Thanks for the report and testing out the software at this stage! Will look into this tomorrow.

**Comment by dtcooper** [comment]
@scottgrobinson If you'd like a fix immediately before the next release, do something like the following in your installation,

```bash
git pull --ff-only

# This may take a while
./compose.sh build app
./compose.sh stop app
./compose up -d app
```

`./compose.sh` just thinly wraps `docker-compose` :)
