### ISSUE TITLE
[FR] Docker container-name prefix

### ISSUE THREAD

**Issue by scottgrobinson** [dtcooper/crazyarms#3]
All containers on our server are prefixed with the "parent" name - I.E "monitoring-"

So when a service called "elastic" spins up, it's container name is actually "monitoring-elastic".

It would be useful if this could be specified within configuration somewhere and automatically applied within crazyarms so when looking down a list of 101 containers, we can easily see the crazyarms containers.

I.E crazyarms-app, crazyarms-db etc.

**Comment by dtcooper** [comment]
Definitely doable. I'll prefix the names tomorrow!
